### PR TITLE
It is a typo? change '=+' to '+='.

### PR DESCRIPTION
**Pull request by Yelen719**

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
Looks like you are right. It seems this wans intended to limit the refresh calls. In the current code this condition is never met due to this typo.

I'd have to check that reintroducing the condition doesn't have an unwanted side-effect.

**Comment by Yelen719** [comment]
Hi Niko,

Thanks for the reply and it’s cool to meet you on GitHub ;).

From my experience this doesn’t  have very much side-effect. But it’s just weird.

Nan

**Comment by NikolausDemmel** [comment]
Ah, it's you :-)

I'll check it out and merge.

**Comment by NikolausDemmel** [comment]
Finally had a look at this again. It seems it doesn't matter anyway if you don't have 10 keyframes or more.

**Pull request merged**
