### PR TITLE
Fix #38 and #39: Solving problems with Visual Studio 2015

### LINKED ISSUE #38: Error building with Visual Studio 2015, probably Boost
I get an error building dso-slam with Visual Studio 2015. The problem may be the usage of the Boost library.
The first error messages are as follows:

>Error	C2061	syntax error: identifier 'function'	dso	C:\XXX\dso-slam\dso\src\util\IndexThreadReduce.h	76	

Line 76 of IndexThreadReduce.h:
`inline void reduce(boost::function<void(int,int,Running*,int)> callPerIndex, int first, int end, int stepSize = 0)
`

The next error is:
>Error	C2143	syntax error: missing ';' before '<'	dso	C:\XXX\dso-slam\dso\src\util\IndexThreadReduce.h	156	

Corresponding code line is:
`boost::function<void(int,int,Running*,int)> callPerIndex;`

CMake (3.8) finds Boost:
>Boost version: 1.63.0
>Found the following Boost libraries:
>  system
>  thread
>  chrono
>  date_time
>  atomic

I had to add `include_directories(${Boost_INCLUDE_DIRS})` after `find_package(Boost COMPONENTS system thread)` in CMakeLists.txt, otherwise the compiler could not include boost/thread.h.

Actually, I don't know where to start to fix this issue. Maybe someone more experienced does have a hint on this. I will provide further information if needed.

Kind regards

### LINKED ISSUE #39: Error building dso-slam with Visual Studio
I get an error building dso-slam with Visual Studio 2015. The first error message is as follows:

>Error	C2976	'std::deque': too few template arguments	dso	C:\XXX\dso-slam\dso\src\FullSystem\FullSystem.h	310	

Line 310 of FullSystem.h:
`std::deque<FrameHessian*> unmappedTrackedFrames;`

Is this related to the the definition of `struct FrameHessian` in HessianBlacks.h?

Actually, I'd like to fix this issue but I don't know where to start searching. Maybe there is someone more experienced that may give a hint on this. What would be useful information to look at?

Kind regards

PS: And why does boost come into play? May this be a hint for an incompatibility to my current boost version (1.63)?
>C:\XXX\dso-slam\dso\src\FullSystem/FullSystem.h(310): error C2976: 'std::deque': too few template arguments
>C:\libs\boost\v1.63.0\boost/detail/container_fwd.hpp(131): note: see declaration of 'std::deque'

### PR DESCRIPTION
**Pull request by wystnphux**
Fix issue #39 with errors building dso-slam with Visual Studio 2015.

### CODE REVIEW

**Comment by jhincapie** [comment]
@wystnphux any chance you can share the VS files?

**Comment by wystnphux** [comment]
@jhincapie: Actually, I did not manage it to fully compile and link. Seems quite difficult - at least on my configuration/machine. Did you have success doing it?

**Comment by jhincapie** [comment]
Hello @wystnphux , I have actually finished compiling for Win 10 x64 using Visual Studio 2015 Community Update 3. It did required minor rewriting of some components and finding the right settings. You can get the code from my fork of the project located at: https://github.com/jhincapie/DSOonWin

**Comment by lcqwe** [comment]
@jhincapie Do you have a try to add some real-time-streaming function into your DSOonWin project? e.g. from a mono camera. I recently tried to implement this, but I don't know how to modify it on windows and no ros environment. (add code into sampleoutput or else?) Hope can give me some prompt, thanks.

**Pull request merged**
